version: '3.9'
x-environment-defaults: &environment-defaults
  SECRET_KEY: "django-insecure-*%&a-^nw%b!c!op0%t5qq#t@y^y^m=(3b_c%i3)3_q6*^a%5m4"
  NAME: "weather"
  USER: "weather"
  PASSWORD: "weather"
  HOST: "db"
  PORT: 5432

services:  
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
      POSTGRES_DB: weather
    ports:
      - "5432:5432"

    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build:
      context: ./weather
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: ./weather
    command: celery -A weather worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      <<: *environment-defaults

  celery-beat:
    build:
      context: ./weather
    command: celery -A weather beat --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      <<: *environment-defaults
